// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class CustomerChurn
{
    /// <summary>
    /// model input class for CustomerChurn.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [LoadColumn(1)]
        [ColumnName(@"Age")]
        public float Age { get; set; }

        [LoadColumn(2)]
        [ColumnName(@"Gender")]
        public string Gender { get; set; }

        [LoadColumn(3)]
        [ColumnName(@"Tenure")]
        public float Tenure { get; set; }

        [LoadColumn(4)]
        [ColumnName(@"Usage Frequency")]
        public float Usage_Frequency { get; set; }

        [LoadColumn(5)]
        [ColumnName(@"Support Calls")]
        public float Support_Calls { get; set; }

        [LoadColumn(6)]
        [ColumnName(@"Payment Delay")]
        public float Payment_Delay { get; set; }

        [LoadColumn(7)]
        [ColumnName(@"Subscription Type")]
        public string Subscription_Type { get; set; }

        [LoadColumn(8)]
        [ColumnName(@"Contract Length")]
        public string Contract_Length { get; set; }

        [LoadColumn(9)]
        [ColumnName(@"Total Spend")]
        public float Total_Spend { get; set; }

        [LoadColumn(10)]
        [ColumnName(@"Last Interaction")]
        public float Last_Interaction { get; set; }

        [LoadColumn(11)]
        [ColumnName(@"Churn")]
        public float Churn { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for CustomerChurn.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"Age")]
        public float Age { get; set; }

        [ColumnName(@"Gender")]
        public float[] Gender { get; set; }

        [ColumnName(@"Tenure")]
        public float Tenure { get; set; }

        [ColumnName(@"Usage Frequency")]
        public float Usage_Frequency { get; set; }

        [ColumnName(@"Support Calls")]
        public float Support_Calls { get; set; }

        [ColumnName(@"Payment Delay")]
        public float Payment_Delay { get; set; }

        [ColumnName(@"Subscription Type")]
        public float[] Subscription_Type { get; set; }

        [ColumnName(@"Contract Length")]
        public float[] Contract_Length { get; set; }

        [ColumnName(@"Total Spend")]
        public float Total_Spend { get; set; }

        [ColumnName(@"Last Interaction")]
        public float Last_Interaction { get; set; }

        [ColumnName(@"Churn")]
        public uint Churn { get; set; }

        [ColumnName(@"Features")]
        public float[] Features { get; set; }

        [ColumnName(@"PredictedLabel")]
        public float PredictedLabel { get; set; }

        [ColumnName(@"Score")]
        public float[] Score { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("CustomerChurn.mlnet");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }

    /// <summary>
    /// Use this method to predict scores for all possible labels.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        var result = predEngine.Predict(input);
        return GetSortedScoresWithLabels(result);
    }

    /// <summary>
    /// Map the unlabeled result score array to the predicted label names.
    /// </summary>
    /// <param name="result">Prediction to get the labeled scores from.</param>
    /// <returns>Ordered list of label and score.</returns>
    /// <exception cref="Exception"></exception>
    public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
    {
        var unlabeledScores = result.Score;
        var labelNames = GetLabels(result);

        Dictionary<string, float> labledScores = new Dictionary<string, float>();
        for (int i = 0; i < labelNames.Count(); i++)
        {
            // Map the names to the predicted result score array
            var labelName = labelNames.ElementAt(i);
            labledScores.Add(labelName.ToString(), unlabeledScores[i]);
        }

        return labledScores.OrderByDescending(c => c.Value);
    }

    /// <summary>
    /// Get the ordered label names.
    /// </summary>
    /// <param name="result">Predicted result to get the labels from.</param>
    /// <returns>List of labels.</returns>
    /// <exception cref="Exception"></exception>
    private static IEnumerable<string> GetLabels(ModelOutput result)
    {
        var schema = PredictEngine.Value.OutputSchema;

        var labelColumn = schema.GetColumnOrNull("Churn");
        if (labelColumn == null)
        {
            throw new Exception("Churn column not found. Make sure the name searched for matches the name in the schema.");
        }

        // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
        var keyNames = new VBuffer<float>();
        labelColumn.Value.GetKeyValues(ref keyNames);
        return keyNames.DenseValues().Select(x => x.ToString());
    }

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }
}
